name: Feature request triage bot

on:
  schedule:
    # Run at 15:00 every day
    - cron: '0 15 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/components'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@b030b2619693d7936a4c67e9773899a79a6f09b7
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
