name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@b030b2619693d7936a4c67e9773899a79a6f09b7
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
